---

- name: install dependencies
  apt:
    name=python-pip
    state=present
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'

- name: install httplib2
  pip:
    name=httplib2
